const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const MatchSchema = new Schema({
    "commentary":{
        type:String,
        required:true
    },
    "competition":{
        "abbr":{
            type:String,
            required:true
        },
        "category":{
            type:String,
            required:true
        },
        "cid":{
            type:Number,
            required:true
        },
        "country":{
            type:String,
            required:true
        },
        "dateend":{
            type:String,
            required:true
        },
        "datestart":{
            type:String,
            required:true
        },
        "match_format":{
            type:String,
            required:true
        },
        "season":{
            type:String,
            required:true
        },
        "status":{
            type:String,
            required:true
        },
        "title":{
            type:String,
            required:true
        },
        "total_matches":{
            type:String,
            required:true
        },
        "total_rounds":{
            type:String,
            required:true
        },
        "total_teams":{
            type:String,
            required:true
        },
        "type":{
            type:String,
            required:true
        }
    },
    "date_end":{
        type:String,
        required:true   
    },
    "date_end_ist":{
        type:String,
        required:true
    },
    "date_start":{
        type:String,
        required:true
    },
    "date_start_ist":{
        type:String,
        required:true
    },
    "domestic":{
        type:String,
        required:true
    },
    "equation":{
        type:String,
        required:true   
    },
    "format":{
        type:Number,
        required:true 
    },
    "format_str":{
        type:String,
        required:true
    },
    "game_state":{
        type:Number,
        required:true
    },
    "game_state_str":{
        type:String,
        required:true
    },
    "latest_inning_number":{
        type:Number,
        required:true
    },
    "live":{
        type:String,
        required:true
    },
    "match_dls_affected":{
        type:String,
        required:true
    },
    "match_id":{
        type:Number,
        required:true
    },
    "match_number":{
        type:String,
        required:true
    },
    "odds_available":{
        type:String,
        required:true
    },
    "pitch":{
        "batting_condition":{
            type:String,
            required:true
        },
        "pace_bowling_condition":{
            type:String,
            required:true
        },
        "pitch_condition":{
            type:String,
            required:true
        },
        "spine_bowling_condition":{
            type:String,
            required:true
        }
    },
    "pre_squad":{
        type:String,
        required:true
    },
    "presquad_time":{
        type:String,
        required:true
    },
    "referee":{
        type:String,
        required:true
    },
    "result":{
        type:String,
        required:true
    },
    "result_type":{
        type:Number,
        required:true
    },
    "short_title":{
        type:String,
        required:true
    },
    "status":{
        type:Number,
        required:true
    },
    "status_note":{
        type:String,
        required:true
    },
    "status_str":{
        type:String,
        required:true
    },
    "subtitle":{
        type:String,
        required:true
    },
    "teama":{
        "logo_url":{
            type:String,
            required:true
        },
        "name":{
            type:String,
            required:true
        },
        "overs":{
            type:String,
            required:true
        },
        "scores":{
            type:String,
            required:true
        },
        "scores_full":{
            type:String,
            required:true
        },
        "short_name":{
            type:String,
            required:true
        },
        "team_id":{
            type:Number,
            required:true
        }
    },
    "teamb":{
        "logo_url":{
            type:String,
            required:true
        },
        "name":{
            type:String,
            required:true
        },
        "overs":{
            type:String,
            required:true
        },
        "scores":{
            type:String,
            required:true
        },
        "scores_full":{
            type:String,
            required:true
        },
        "short_name":{
            type:String,
            required:true
        },
        "team_id":{
            type:Number
        }
    },
    "timestamp_end":{
        type:Number,
        required:true
    },
    "timestamp_start":{
        type:Number,
        required:true
    },
    "title":{
        type:String,
        required:true  
    },
    "toss":{
        "decision":{
            type:Number,
            required:true
        },
        "text":{
            type:String,
            required:true
        },
        "winner":{
            type:Number,
            required:true
        }
    },
    "umpires":{
        type:String,
        required:true
    },
    "venue":{
        "country":{
            type:String,
            required:true
        },
        "location":{
            type:String,
            required:true
        },
        "name":{
            type:String,
            required:true
        },
        "timezone":{
            type:String,
            required:true
        },
        "venue_id":{
            type:String,
            required:true
        }
    },
    "verified":{
        type:String,
        required:true
    },
    "verify_time":{
        type:String,
        required:true
    },
    "wagon":{
        type:Number,
        required:true
    },
    "weather":{
        type:Array,
        required:true
    },
    "win_margin":{
        type:String,
        required:true
    },
    "winning_team_id":{
        type:Number,
        required:true
    }
});

module.exports = mongoose.model("matchDataHandel",MatchSchema,"matchDetails");